### ISSUE TITLE
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

### ISSUE THREAD

**Issue by wangxiao5791509** [ZZUTK/Face-Aging-CAAE#1]
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 1 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 1:   Y Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:1) -> (device: 1, name: GeForce GTX 1080, pci bus id: 0000:02:00.0)

	Building graph ...
Traceback (most recent call last):
  File "main.py", line 43, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 27, in main
    dataset_name=FLAGS.dataset  # name of the dataset in the folder ./data
  File "/home/wangxiao/Downloads/Face-Aging-CAAE-master/FaceAging.py", line 91, in __init__
    tile_ratio=self.tile_ratio
  File "/home/wangxiao/Downloads/Face-Aging-CAAE-master/FaceAging.py", line 474, in generator
    z = concat_label(z, y, duplicate=duplicate)
  File "/home/wangxiao/Downloads/Face-Aging-CAAE-master/ops.py", line 76, in concat_label
    return tf.concat(1, [x, label])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1029, in concat
    dtype=dtypes.int32).get_shape(
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 637, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 702, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 110, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 99, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 367, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

**Comment by wangxiao5791509** [comment]
I have solved this issue ! Thanks.

**Comment by Cloudox** [comment]
How to solve？

**Comment by MichaelXin** [comment]
The same question. Could you tell me how to solve it? Thanks!  @wangxiao5791509

**Comment by wangxiao5791509** [comment]
@MichaelXin   you can see this : https://github.com/wangxiao5791509/Age-Progression-Regression-by-CAAE

**Comment by MichaelXin** [comment]
Thanks! It works @wangxiao5791509
