### ISSUE TITLE
ValueError: Variable E_conv0/w/Adam/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

### ISSUE THREAD

**Issue by Paseam** [ZZUTK/Face-Aging-CAAE#2]
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 960, pci bus id: 0000:01:00.0)

	Building graph ...

	Training Mode
Traceback (most recent call last):
  File "main.py", line 43, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 32, in main
    num_epochs=FLAGS.epoch,  # number of epochs
  File "/paseam/git/Face-Aging-CAAE/FaceAging.py", line 224, in train
    var_list=self.E_variables + self.G_variables
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 298, in minimize
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 412, in apply_gradients
    self._create_slots(var_list)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/adam.py", line 119, in _create_slots
    self._zeros_slot(v, "m", self._name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 656, in _zeros_slot
    named_slots[var] = slot_creator.create_zeros_slot(var, op_name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/slot_creator.py", line 123, in create_zeros_slot
    colocate_with_primary=colocate_with_primary)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/slot_creator.py", line 101, in create_slot
    return _create_slot_var(primary, val, '')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/slot_creator.py", line 55, in _create_slot_var
    slot = variable_scope.get_variable(scope, initializer=val, trainable=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 988, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 890, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 348, in get_variable
    validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 333, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 657, in _get_single_variable
    "VarScope?" % name)
ValueError: Variable E_conv0/w/Adam/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

**Comment by Paseam** [comment]
solved thx

**Comment by PHPerWu** [comment]
How can you solved it?

**Comment by GraceDD** [comment]
@Paseam Hello, I met the same problem as you above. Could you tell me how you solved it ? My tensorflow version is 1.0

**Comment by Hellomodo** [comment]
this problem is caused by the leaky reuse。
refer to [https://github.com/tensorflow/tensorflow/issues/6220](url)
so please put variable_scope around the place you call reuse_varables()

**Comment by leivo** [comment]
Make the following modifications in _FaceAging.py_ to solve this problem:
```
    def encoder(self, image, reuse_variables=False):
        **with tf.variable_scope("encoder") as scope:**
            if reuse_variables:
            ......
```

```
    def generator(self, z, y, gender, reuse_variables=False, enable_tile_label=True, tile_ratio=1.0):
        **with tf.variable_scope("generator") as scope:**
            if reuse_variables:
            ......
```

```
    def discriminator_z(self, z, is_training=True, reuse_variables=False, num_hidden_layer_channels=(64, 32, 16), enable_bn=True):
        **with tf.variable_scope("discriminator_z") as scope:**
            if reuse_variables:
            ......
```

```
    def discriminator_img(self, image, y, gender, is_training=True, reuse_variables=False, num_hidden_layer_channels=(16, 32, 64, 128), enable_bn=True):
        **with tf.variable_scope("discriminator_img") as scope:**
            if reuse_variables:
            ......
```
