### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'AUTO_REUSE'

### ISSUE THREAD

**Issue by mrazimi** [ZZUTK/Face-Aging-CAAE#35]
Training Mode
Traceback (most recent call last):
  File "main.py", line 70, in <module>
    tf.app.run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 59, in main
    use_init_model=FLAGS.use_init_model
  File "C:\Users\user\Downloads\Face-Aging-CAAE-master\FaceAging.py", line 218, in train
    with tf.variable_scope('opt', reuse=tf.AUTO_REUSE):
AttributeError: module 'tensorflow' has no attribute 'AUTO_REUSE'

**Comment by mrazimi** [comment]
pip3 install --upgrade tensorflow

**Comment by dimitri320** [comment]
this doesn't work in Oct 2019

**Comment by RushToNeverLand** [comment]
this doesn't work in Oct 2019

**Comment by RushToNeverLand** [comment]
this doesn't work in Dec 2019

**Comment by jqueguiner** [comment]
to fix :  use tf.compat.v1.AUTO_REUSE instead
