### ISSUE TITLE
AttributeError: 'SymbolDatabase' object has no attribute 'RegisterServiceDescriptor'

### ISSUE THREAD

**Issue by ghost** [ZZUTK/Face-Aging-CAAE#39]
PS C:\Users\user\Downloads\Face-Aging-CAAE-master> python main.py
C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Namespace(dataset='UTKFace', epoch=50, is_train=True, savedir='save', testdir='None', use_init_model=True, use_trained_model=True)
        Building graph ...
Traceback (most recent call last):
  File "main.py", line 70, in <module>
    tf.app.run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "main.py", line 43, in main
    dataset_name=FLAGS.dataset  # name of the dataset in the folder ./data
  File "C:\Users\user\Downloads\Face-Aging-CAAE-master\FaceAging.py", line 95, in __init__
    is_training=self.is_training
  File "C:\Users\user\Downloads\Face-Aging-CAAE-master\FaceAging.py", line 554, in discriminator_z
    current = tf.contrib.layers.batch_norm(
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\util\lazy_loader.py", line 53, in __getattr__
    module = self._load()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\util\lazy_loader.py", line 42, in _load
    module = importlib.import_module(self.__name__)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\__init__.py", line 39, in <module>
    from tensorflow.contrib import distributions
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\distributions\__init__.py", line 40, in <module>
    from tensorflow.contrib.distributions.python.ops.estimator import *
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\distributions\python\ops\estimator.py", line 21, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.head import _compute_weighted_loss
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\learn\__init__.py", line 95, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\learn\python\__init__.py", line 28, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\learn\python\learn\__init__.py", line 40, in <module>
    from tensorflow.contrib.learn.python.learn.experiment import Experiment
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\learn\python\learn\experiment.py", line 39, in <module>
    from tensorflow.contrib.tpu.python.tpu import tpu_estimator
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\tpu\__init__.py", line 55, in <module>
    from tensorflow.contrib.tpu.python import profiler
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\tpu\python\profiler\__init__.py", line 23, in <module>
    from tensorflow.contrib.tpu.profiler.tpu_profiler_analysis_pb2 import *
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\tpu\profiler\tpu_profiler_analysis_pb2.py", line 16, in <module>
    from tensorflow.contrib.tpu.profiler import tpu_profiler_pb2 as tensorflow_dot_contrib_dot_tpu_dot_profiler_dot_tpu__profiler__pb2
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\tpu\profiler\tpu_profiler_pb2.py", line 402, in <module>
    _sym_db.RegisterServiceDescriptor(_TPUPROFILER)
AttributeError: 'SymbolDatabase' object has no attribute 'RegisterServiceDescriptor'
PS C:\Users\user\Downloads\Face-Aging-CAAE-master> python main.py
C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Namespace(dataset='UTKFace', epoch=50, is_train=True, savedir='save', testdir='None', use_init_model=True, use_trained_model=True)

        Building graph ...
Traceback (most recent call last):
  File "main.py", line 70, in <module>
    tf.app.run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "main.py", line 43, in main
    dataset_name=FLAGS.dataset  # name of the dataset in the folder ./data
  File "C:\Users\user\Downloads\Face-Aging-CAAE-master\FaceAging.py", line 95, in __init__
    is_training=self.is_training
  File "C:\Users\user\Downloads\Face-Aging-CAAE-master\FaceAging.py", line 554, in discriminator_z
    current = tf.contrib.layers.batch_norm(
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\util\lazy_loader.py", line 53, in __getattr__
    module = self._load()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\util\lazy_loader.py", line 42, in _load
    module = importlib.import_module(self.__name__)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\__init__.py", line 39, in <module>
    from tensorflow.contrib import distributions
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\distributions\__init__.py", line 40, in <module>
    from tensorflow.contrib.distributions.python.ops.estimator import *
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\distributions\python\ops\estimator.py", line 21, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.head import _compute_weighted_loss
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\learn\__init__.py", line 95, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\learn\python\__init__.py", line 28, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\learn\python\learn\__init__.py", line 40, in <module>
    from tensorflow.contrib.learn.python.learn.experiment import Experiment
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\learn\python\learn\experiment.py", line 39, in <module>
    from tensorflow.contrib.tpu.python.tpu import tpu_estimator
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\tpu\__init__.py", line 55, in <module>
    from tensorflow.contrib.tpu.python import profiler
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\tpu\python\profiler\__init__.py", line 23, in <module>
    from tensorflow.contrib.tpu.profiler.tpu_profiler_analysis_pb2 import *
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\tpu\profiler\tpu_profiler_analysis_pb2.py", line 16, in <module>
    from tensorflow.contrib.tpu.profiler import tpu_profiler_pb2 as tensorflow_dot_contrib_dot_tpu_dot_profiler_dot_tpu__profiler__pb2
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\tpu\profiler\tpu_profiler_pb2.py", line 402, in <module>
    _sym_db.RegisterServiceDescriptor(_TPUPROFILER)
AttributeError: 'SymbolDatabase' object has no attribute 'RegisterServiceDescriptor'

**Comment by ghost** [comment]
tensorflow 1.7 is needed, for higher versions it doesnt work!
