### ISSUE TITLE
Problems when running the model

### ISSUE THREAD

**Issue by Konstallation** [ZZUTK/Face-Aging-CAAE#8]
Hello~
When I am running your code,the error look like this
![image](https://cloud.githubusercontent.com/assets/27912505/26006618/b017c4ca-376f-11e7-963c-03fbe791e0ff.png)
I don't know where go wrong,Could you help me ?

**Comment by tianjiaoer** [comment]
Hello~！！
Hello~！！
me too 
![image](https://cloud.githubusercontent.com/assets/24488705/26025793/c3ea3412-3821-11e7-9372-0100933c9f32.png)
who can tell me ?

**Comment by akakakakakaa** [comment]
Maybe Dataset image must be in a folder named UTKFace

**Comment by superjiajia26** [comment]
I have the same questions too.Can you tell me how to solve this problem?     Thank you very much~~~
Traceback (most recent call last):
  File "/home/lj/CAAE/main.py", line 43, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/home/lj/CAAE/main.py", line 32, in main
    num_epochs=FLAGS.epoch,  # number of epochs
  File "/home/lj/CAAE/FaceAging.py", line 424, in train
    self.sample(sample_images, sample_label_age, sample_label_gender, name)
  File "/home/lj/CAAE/FaceAging.py", line 634, in sample
    self.gender: gender
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 943, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (0,) for Tensor u'input_images:0', which has shape '(100, 128, 128, 3)'

Hope for your replying!

**Comment by taehee33** [comment]
Put the utkFace folder in the data Folder

**Comment by ajaysimhasr** [comment]
Hi,

I am running your code on Ubuntu 16.0.4.

Even I am facing the same error as above. The 'UTKFace' dataset is inside the folder 'data'. Still I have this issue.

Can you help me with this please?

Error Log:

$ python main.py 

Namespace(dataset='UTKFace', epoch=50, is_train=True, savedir='save', testdir='None', use_init_model=True, use_trained_model=True)

	Building graph ...

	Training Mode

	Loading pre-trained model ...
	FAILED >_<!

	Loading init model ...
Traceback (most recent call last):
  File "main.py", line 70, in <module>
    tf.app.run()
  File "/home/codas/anaconda3/envs/MITA_2018_Capstone/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "main.py", line 59, in main
    use_init_model=FLAGS.use_init_model
  File "/home/codas/Documents/Ajay/MITA_2018_Capstone/Tensorflow_AgeProgression/Face-Aging-CAAE/FaceAging.py", line 435, in train
    self.sample(sample_images, sample_label_age, sample_label_gender, name)
  File "/home/codas/Documents/Ajay/MITA_2018_Capstone/Tensorflow_AgeProgression/Face-Aging-CAAE/FaceAging.py", line 652, in sample
    self.gender: gender
  File "/home/codas/anaconda3/envs/MITA_2018_Capstone/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/codas/anaconda3/envs/MITA_2018_Capstone/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1128, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (0,) for Tensor 'input_images:0', which has shape '(100, 128, 128, 3)'

**Comment by ArashHosseini** [comment]
@ajaysimhasr https://github.com/ZZUTK/Face-Aging-CAAE/blob/d59275f00af647c8fc333f79c016fb9cf69d4c7b/FaceAging.py#L195 requires a flat list of images, your UTKFace folder shouldn't contain nothing else then images

**Comment by Alzahraa-Ahmed** [comment]
Hi, Where to download the pre-trained model?
